import Image1 from './images/nfts-1.jpg'
import Image2 from './images/nfts-2.jpg'
import Image3 from './images/nfts-3.jpg'
import Image4 from './images/nfts-4.jpg'
import Logos from './images/logos.png'

export const nfts = [
  {
    id: '1',
    src: Image1.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'epic',
  },
  {
    id: '2',
    src: Image2.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Rare',
    logos: Logos.src,
    color: 'rare',
  },
  {
    id: '3',
    src: Image3.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'One of a kind',
    logos: Logos.src,
    color: 'one-of-a-kind',
  },
  {
    id: '4',
    src: Image4.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'signature',
  },
  {
    id: '5',
    src: Image1.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'epic',
  },
  {
    id: '6',
    src: Image2.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Rare',
    logos: Logos.src,
    color: 'rare',
  },
  {
    id: '7',
    src: Image3.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'One of a kind',
    logos: Logos.src,
    color: 'one-of-a-kind',
  },
  {
    id: '8',
    src: Image4.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'signature',
  },
  {
    id: '1',
    src: Image1.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'epic',
  },
  {
    id: '2',
    src: Image2.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Rare',
    logos: Logos.src,
    color: 'rare',
  },
  {
    id: '3',
    src: Image3.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'One of a kind',
    logos: Logos.src,
    color: 'one-of-a-kind',
  },
  {
    id: '4',
    src: Image4.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'signature',
  },
  {
    id: '5',
    src: Image1.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'epic',
  },
  {
    id: '6',
    src: Image2.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Rare',
    logos: Logos.src,
    color: 'rare',
  },
  {
    id: '7',
    src: Image3.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'One of a kind',
    logos: Logos.src,
    color: 'one-of-a-kind',
  },
  {
    id: '8',
    src: Image4.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'signature',
  },
  {
    id: '1',
    src: Image1.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'epic',
  },
  {
    id: '2',
    src: Image2.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Rare',
    logos: Logos.src,
    color: 'rare',
  },
  {
    id: '3',
    src: Image3.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'One of a kind',
    logos: Logos.src,
    color: 'one-of-a-kind',
  },
  {
    id: '4',
    src: Image4.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'signature',
  },
  {
    id: '5',
    src: Image1.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'epic',
  },
  {
    id: '6',
    src: Image2.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Rare',
    logos: Logos.src,
    color: 'rare',
  },
  {
    id: '7',
    src: Image3.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'One of a kind',
    logos: Logos.src,
    color: 'one-of-a-kind',
  },
  {
    id: '8',
    src: Image4.src,
    title: 'K 4 Race edition #1',
    price: '$20',
    rarity: 'Epic',
    logos: Logos.src,
    color: 'signature',
  },
]
