import type { Metadata } from 'next'
import classNames from 'classnames'
import { IBM_FLEX_SANS, Whyte } from './fonts'
import 'swiper/css/bundle'
// import 'swiper/css'
// import 'swiper/css/effect-fade'
// import 'swiper/css/free-mode'
// import 'swiper/css/navigation'
// import 'swiper/css/thumbs'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import './App.scss'
import { Footer, Header } from 'widgets'
import { Providers } from './Providers'
import { Box } from '@mui/material'
import './api/nfts/db'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={classNames(IBM_FLEX_SANS.variable, Whyte.variable)}>
        <Providers>
          <Header />
          <Box sx={{ height: { lg: '85px', xs: '60px' } }}></Box>
          <Box
            component={'main'}
            maxWidth={1920}
            mx={'auto'}
            overflow={'hidden'}
            position={'relative'}
            minHeight={{ lg: 900, xs: 'auto' }}
          >
            {children}
          </Box>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
