export const nft = {
  item: {
    id: 11,
    nft_name: 'Signature Edition',
    name: 'K4 Signature Edition #1 - Christof Klausner Memorial',
    description:
      'In memory of a person who embodied the love of rallying, Christof Klausner. This NFT is based on the design of his legendary rally car which he used for 14 years. It is a tribute to a true drift specialist and a very sympathetic sportsman.',
    image: 'car/Primal1.jpg',
    video: 'Primal1_720p.mp4',
    model: 'Primal1',
    contract_name: 'K4 NFT Car - Signature Edition #1',
    rarity: 'Signature',
    brl_class: 0,
    price: '100.00',
    total_amount: 1000,
    mint_count: 6,
    show_in_marketplace: 1,
    homepage_order: 3,
    chains: [
      {
        id: 11,
        chain: 'bsc',
        value: 56,
        coins: 'BNB,BUSD',
        contract_address: '0x52718219aac5144d2fbdbef7e0df706fc39002c5',
        label: 'Binance Smart Chain (BEP20)',
      },
      {
        id: 12,
        chain: 'polygon',
        value: 137,
        coins: 'MATIC,USDC',
        contract_address: '0x22645d386f926795d8f376665651f473863d79ae',
        label: 'Polygon',
      },
      {
        id: 15,
        chain: 'eth',
        value: 1,
        coins: 'ETH,DAI',
        contract_address: '0xe0c820465a97ba8779afe8954e84cf548ec7a357',
        label: 'Ethereum Mainnet',
      },
      {
        id: 21,
        chain: 'okc',
        value: 66,
        coins: 'OKT',
        contract_address: '0x7f30bdbc90ccd8ba70677c5676e3ad9a77f96804',
        label: 'OKX Chain',
      },
    ],
    template: {
      prefab: 'Klausner',
      level: 1,
      acceleration: 1,
      agility: 1,
      braking: 1,
      drift: 1,
      drive_type: 'AWD',
      endurance: 1,
      speed: 1,
      stability: 1,
      acceleration_boosts: 0,
      agility_boosts: 0,
      braking_boosts: 0,
      drift_boosts: 1,
      endurance_boosts: 0,
      speed_boosts: 0,
      stability_boosts: 0,
      total_boosts: 1,
      used_boosts: 1,
      part_slots: 5,
      k4r_reward_bonus: 0,
      brl_daily_drop_bonus: 0,
      brl_tournament_fees_reduction: 0,
    },
  },
}
